@startuml
'C4 templates
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

'sprites
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!include AzurePuml/AzureCommon.puml
!include AzurePuml/Databases/AzureCosmosDb.puml
!include AzurePuml/Compute/AzureFunction.puml

'show person as an outline and not a block
SHOW_PERSON_OUTLINE()

'define style
AddElementTag("personTag", $bgColor="IndianRed", $fontColor="black", $borderColor="IndianRed",$legendText="Customer (End-User)")
AddElementTag("azureComponent", $bgColor="teal", $borderColor="teal", $fontColor="white", $legendText="Azure Component")
AddElementTag("vendorApplication", $bgColor="grey", $borderColor="grey", $fontColor="white", $legendText="External Vendor Application")
AddElementTag("endUserDevice", $bgColor="black", $borderColor="black",$fontColor="white", $legendText="End User Device (Phone)")
AddRelTag("in", $textColor="green", $lineColor="green", $legendText="Egress Transactions (Input Flow from User)")
AddRelTag("out", $textColor="red", $lineColor="red", $legendText="Ingress Transactions (System Output Flow to User)")
AddRelTag("internal", $textColor="black", $lineColor="black", $legendText="Internal Processing (No User Impact)")

'define title
'title Component Diagram for Mobile Banking Application - Account Transfer Flow
 
'person
Person(mobileBankingCustomer,"Online Banking Customer", "Customer", $tags="personTag")

'components

Deployment_Node_L(apiOne, "input values"){
    AddProperty("id","1")
}

Deployment_Node(apiTwo, "input values"){
    AddProperty("id","1")
}

Deployment_Node_L(apiInput, "API Input")
Container(ma, "Mobile App", "Flutter", "Provides banking functionality to service account through a mobile application written in Flutter giving a similar experience on Android and iOS", $tags="endUserDevice")

Component(okta, "Identity Provider" , "Okta", "Identity provider and authorization server", $tags="vendorApplication")

Deployment_Node_L(azure,"Clound Tenant", "Azure"){
    Container(apiGateway, "API Gateway", "Azure API Management", "Leveraging the API gateway functionality of the Azure API Management product, the gateway acts a centralized proxy for all internal and external API integrations", $tags="azureComponent")
    Deployment_Node_L(serverlessPlatform, "Serverless Platform", "Azure Functions", "Azure Functions is a serverless platform to host functions with endpoints exposed as REST APIs."){
        Component(microserviceUpdate, "Audit Banking Transactions", "Microservice", "Severless Golang function that leverages an HTTP trigger", $tags="azureComponent")
    }
    Component(cosmosDb, "Audit Database", "Cosmos DB", "Audit database of transactions for banking money movement. Syncs with Banking Core and Payments Platform.", $tags="azureComponent")
}

Component(bankingCore, "Banking Core System", "SaaS", "OpenAPI banking core system to manage transactions, transfers, and ledger information for banking users.", $tags="vendorApplication")

'relationships that are indexed for auto numbering
RelIndex_R(Index(), mobileBankingCustomer, ma, "User enters username and password.", $tags="in") 
RelIndex_U(Index(), ma, okta, "Identity provider validates user via OAuth2 flow.", $tags="in")
RelIndex_D(Index(), okta, ma, "Identity provider returns access token.", $tags='out')
RelIndex_L(Index(), ma, mobileBankingCustomer, "User is authenticated.", $tags='out')
RelIndex_R(Index(), mobileBankingCustomer, ma, "User requests transfer of $1,000 from Checking Account to Savings Account", $tags='in')
RelIndex_R(Index(), ma, apiGateway, "API request to initiate account transfer", "HTTP /POST", $tags="in")
RelIndex_D(Index(), apiGateway, microserviceUpdate, "Routes request to backend microservice", "HTTP /POST", $tags="internal")
RelIndex_L(Index(), bankingCore, apiGateway, "Returns success message with latest balances", "201 Accepted", $tags="out")
RelIndex_R(Index(), apiGateway, bankingCore, "Routes HTTP /POST request to update balance in banking core", $tags="in")
RelIndex_D(Index(), microserviceUpdate,cosmosDb, "Update transaction and balance information", $tags="internal")
RelIndex_L(Index(), apiGateway, ma, "Return success message with latest balances", "201 Accepted", $tags="out")
RelIndex_L(Index(), ma, mobileBankingCustomer, "Message showing transfer is complete with latest balences", $tags="out")

SHOW_LEGEND()
@enduml
